# Generated by Django 3.1.6 on 2021-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
