# Generated by Django 3.1.6 on 2021-03-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20210310_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weblog.author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weblog.blog'),
        ),
    ]
