# Generated by Django 4.0.2 on 2022-02-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (0, 'female')], max_length=2, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('id_card', models.CharField(max_length=18, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('hire_date_time', models.DateTimeField()),
                ('working_year', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for drug.', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='The drug name.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='The drug info description.')),
                ('price', models.FloatField(blank=True, help_text='The drug price.')),
                ('drug_thumbnail', models.ImageField(blank=True, upload_to='medical/images/drug/thumbnail')),
                ('produced_date_time', models.DateTimeField(help_text='The drug produced date time.')),
                ('onboard_date_time', models.DateTimeField(help_text='The drug onboard date time.')),
                ('sales_volume', models.FloatField(help_text='The drug sales volume.')),
            ],
            options={
                'verbose_name': 'drug',
                'verbose_name_plural': 'drugs',
                'ordering': ['onboard_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The equipment trade mark.', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='Equipment name.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code for hospital', max_length=200, unique=True)),
                ('name', models.CharField(help_text='The name for hospital.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NucleicAcidTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (0, 'female')], max_length=2, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('id_card', models.CharField(max_length=18, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('hire_date_time', models.DateTimeField()),
                ('working_year', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (0, 'female')], max_length=2, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('id_card', models.CharField(max_length=18, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='The longitude for hospital.')),
                ('latitude', models.FloatField(help_text='The latitude for hospital location.')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (0, 'female')], max_length=2, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('id_card', models.CharField(max_length=18, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(help_text='The office builder code number', max_length=200, unique=True)),
                ('related_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='related_hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.region'),
        ),
        migrations.CreateModel(
            name='BuildrArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(help_text='The office builder code number', max_length=200, unique=True)),
                ('related_office_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital')),
            ],
        ),
    ]
