# Generated by Django 4.0.2 on 2022-04-23 09:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical.extend.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(help_text='The office builder code number', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='COVIDActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('process_date_time', models.DateTimeField()),
                ('publish_date_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(blank=True, max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('work_year', models.PositiveIntegerField(help_text='The years of working.')),
                ('hire_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('education_background', medical.extend.fields.EducationBackgroundField(choices=[(0, 'undergraduate（本科）'), (1, 'junior（专科）'), (2, 'senior（高中）'), (3, 'junior（初中）')], max_length=20)),
                ('doctor_qualification', models.IntegerField(choices=[(1, '住院医师（助教）'), (2, '主治医师（讲师）'), (3, '副主任医师（副教授）'), (4, '主任医师（教授）')])),
                ('related_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.buildarea')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for drug.', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='The drug name.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='The drug info description.')),
                ('price', models.FloatField(blank=True, help_text='The drug price.')),
                ('drug_thumbnail', models.ImageField(blank=True, upload_to='medical/images/drug/thumbnail')),
                ('produced_date_time', models.DateTimeField(help_text='The drug produced date time.')),
                ('onboard_date_time', models.DateTimeField(help_text='The drug onboard date time.')),
                ('sales_volume', models.FloatField(help_text='The drug sales volume.')),
            ],
            options={
                'verbose_name': 'drug',
                'verbose_name_plural': 'drugs',
                'ordering': ['onboard_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The equipment trade mark.', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='Equipment name.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='The longitude for hospital.')),
                ('latitude', models.FloatField(help_text='The latitude for hospital location.')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('email', models.EmailField(max_length=254)),
                ('telphone', medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate])),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('last_visit_site_time', models.DateTimeField(default=datetime.datetime(2022, 4, 23, 17, 25, 11, 810918), null=True)),
                ('visit_times', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('covidactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medical.covidactivity')),
                ('amount_of_subscribe', models.PositiveIntegerField()),
                ('amount_of_vaccine', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('medical.covidactivity',),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(blank=True, max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('work_year', models.PositiveIntegerField(help_text='The years of working.')),
                ('hire_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('support_type', models.IntegerField(choices=[(1, '临时工'), (2, '外派人员'), (3, '正式员工')])),
                ('work_date', models.DateTimeField()),
                ('is_student', models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0)),
                ('no_salary', models.IntegerField(choices=[(0, '无'), (1, '有')], default=0)),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.covidactivity')),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(blank=True, max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('work_year', models.PositiveIntegerField(help_text='The years of working.')),
                ('hire_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('support_type', models.IntegerField(choices=[(1, '临时工'), (2, '外派人员'), (3, '正式员工')])),
                ('due_description', models.TextField(blank=True, help_text='职责描述', max_length=200)),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('email', models.EmailField(max_length=254)),
                ('telphone', medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate])),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('related_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.buildarea')),
                ('related_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', medical.extend.fields.GenderField(choices=[(1, 'male'), (0, 'female')], max_length=20, null=True)),
                ('age', medical.extend.fields.AgeField(blank=True, max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate])),
                ('work_year', models.PositiveIntegerField(help_text='The years of working.')),
                ('hire_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='medical/images/common_people/profile')),
                ('education_background', medical.extend.fields.EducationBackgroundField(choices=[(0, 'undergraduate（本科）'), (1, 'junior（专科）'), (2, 'senior（高中）'), (3, 'junior（初中）')], max_length=20)),
                ('nurse_qualification', models.IntegerField(choices=[(1, '初级护士'), (2, '中级护士'), (3, '高级护士')])),
                ('related_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code for hospital.', max_length=200, unique=True)),
                ('name', models.CharField(help_text='The name for hospital.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='The description for hospital.')),
                ('related_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.region')),
            ],
        ),
        migrations.AddField(
            model_name='buildarea',
            name='related_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital'),
        ),
        migrations.CreateModel(
            name='VaccinationSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('telephone', models.CharField(help_text='请输入 +08-XXXXXXXXXXX', max_length=200, null=True, verbose_name='手机号码')),
                ('email_address', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='家庭住址')),
                ('birth', models.DateField(verbose_name='出生日期')),
                ('person_photo', models.FileField(blank=True, upload_to='', verbose_name='个人照片')),
                ('related_vaccination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical.vaccination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vaccination',
            name='related_builder_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.buildarea'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='related_vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.vaccine'),
        ),
    ]
