# Generated by Django 4.0.2 on 2022-02-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildrArea',
            new_name='BuildArea',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='related_hospital',
            new_name='related_region',
        ),
    ]
