# Generated by Django 4.0.2 on 2022-04-23 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical.extend.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncreaseVirusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definite', models.PositiveIntegerField(verbose_name='确诊')),
                ('cure', models.PositiveIntegerField(verbose_name='本土')),
                ('dead', models.PositiveIntegerField(verbose_name='境外输入')),
                ('asymptomatic', models.PositiveIntegerField(verbose_name='无症状')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticsVirusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definite', models.PositiveIntegerField(verbose_name='确诊')),
                ('cure', models.PositiveIntegerField(verbose_name='治愈')),
                ('dead', models.PositiveIntegerField(verbose_name='死亡')),
            ],
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={},
        ),
        migrations.AddField(
            model_name='drug',
            name='storage_volume',
            field=models.FloatField(blank=True, default=0, help_text='存储量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='drug_thumbnail',
            field=models.ImageField(blank=True, upload_to='medical/images/equipment/thumbnail'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='onboard_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='produced_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='sales_volume',
            field=models.FloatField(blank=True, default=0, help_text='销售量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_volume',
            field=models.FloatField(blank=True, default=0, help_text='存储量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='sales_volume',
            field=models.FloatField(blank=True, help_text='销售量'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telphone',
            field=medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit_site_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 18, 21, 50, 694293), null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='telphone',
            field=medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_student',
            field=models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否是学生'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='no_salary',
            field=models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, verbose_name='是否需要工资'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='related_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.covidactivity', verbose_name='报名参加的活动'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_date',
            field=models.DateTimeField(help_text='选择你要工作的日期时间', verbose_name='工作日期'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url_path', models.FileField(blank=True, upload_to='')),
                ('title', models.TextField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('publish_date_time', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
