# Generated by Django 4.0.2 on 2022-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_rename_buildrarea_buildarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officearea',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
