# Generated by Django 4.0.2 on 2022-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_officearea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildarea',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
