# Generated by Django 4.0.2 on 2022-02-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_buildarea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildarea',
            name='related_office_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.officearea'),
        ),
    ]
