# Generated by Django 4.0.2 on 2022-05-02 04:02

import datetime
from django.db import migrations, models
import medical.extend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_doctor_age_alter_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telphone',
            field=medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit_site_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 12, 2, 14, 78507), null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='telphone',
            field=medical.extend.fields.TelPhoneField(max_length=104, validators=[medical.extend.fields.TelPhoneField.tel_phone_validate, medical.extend.fields.TelPhoneField.tel_phone_validate]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=medical.extend.fields.AgeField(max_length=20, validators=[medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate, medical.extend.fields.AgeField.age_validate]),
        ),
    ]
