# Generated by Django 4.0.2 on 2022-02-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_vaccination_amount_of_subscribe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date_time', models.DateTimeField()),
                ('name', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('related_vaccination', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical.vaccination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
