# Generated by Django 4.0.2 on 2022-03-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_vaccinationsubscribe_subscribe_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationsubscribe',
            name='related_vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical.vaccination'),
        ),
    ]
