# Generated by Django 4.0.2 on 2022-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_alter_vaccinationsubscribe_related_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationsubscribe',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='vaccinationsubscribe',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='vaccinationsubscribe',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='vaccinationsubscribe',
            name='telephone',
            field=models.CharField(max_length=200, null=True, verbose_name='手机号码'),
        ),
    ]
