# Generated by Django 4.0.2 on 2022-03-17 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_vaccinationsubscribe_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationsubscribe',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出生日期'),
            preserve_default=False,
        ),
    ]
