# Generated by Django 4.0.2 on 2022-03-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_vaccinationsubscribe_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationsubscribe',
            name='person_photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='个人照片'),
        ),
    ]
