# Generated by Django 4.0.2 on 2022-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_vaccinationsubscribe_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, help_text='The description for hospital.'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(help_text='The code for hospital.', max_length=200, unique=True),
        ),
    ]
