# Generated by Django 4.0.2 on 2022-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
