# Generated by Django 4.0.2 on 2022-05-01 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='open_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 39, 19, 147998)),
            preserve_default=False,
        ),
    ]
