# Generated by Django 4.0.2 on 2022-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_officialaccount_description_officialaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
