# Generated by Django 4.0.2 on 2022-05-02 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_doctor_age_alter_nurse_age_alter_patient_age_and_more'),
        ('chat', '0002_chatroom_open_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationChatRoom',
            fields=[
                ('chatroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatroom')),
                ('related_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.vaccination')),
            ],
            bases=('chat.chatroom',),
        ),
    ]
