# Generated by Django 4.0.2 on 2022-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_officialaccount_related_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='auto_replay_configs',
            field=models.ManyToManyField(blank=True, to='chat.AutoReply'),
        ),
    ]
