# Generated by Django 4.0.2 on 2022-05-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_autoreply_officialaccount_auto_replay_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialchatroom',
            name='related_official_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.officialaccount'),
        ),
    ]
